name: "Build"

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  prepare:
    name: prepare
    runs-on: ubuntu-slim
    permissions:
      contents: read
      packages: read
      pull-requests: write
    outputs:
      changed-moose-base-rocky8: ${{ steps.parse.outputs.changed-moose-base-rocky8 }}
      changed-moose-base-rocky9: ${{ steps.parse.outputs.changed-moose-base-rocky9 }}
      changed-moose-base-rocky8-cuda: ${{ steps.parse.outputs.changed-moose-base-rocky8-cuda }}
      changed-moose-base-ubuntu24: ${{ steps.parse.outputs.changed-moose-base-ubuntu24 }}
      changed-moose-base-ubuntu24-cuda: ${{ steps.parse.outputs.changed-moose-base-ubuntu24-cuda }}
      changed-moose-compiler-rocky8-cuda-gcc: ${{ steps.parse.outputs.changed-moose-compiler-rocky8-cuda-gcc }}
      changed-moose-compiler-rocky8-gcc: ${{ steps.parse.outputs.changed-moose-compiler-rocky8-gcc }}
      changed-moose-compiler-rocky9-gcc: ${{ steps.parse.outputs.changed-moose-compiler-rocky9-gcc }}
      changed-moose-compiler-ubuntu24-gcc: ${{ steps.parse.outputs.changed-moose-compiler-ubuntu24-gcc }}
      changed-moose-compiler-ubuntu24-cuda-gcc: ${{ steps.parse.outputs.changed-moose-compiler-ubuntu24-cuda-gcc }}
      changed-moose-mpi-rocky8-clang: ${{ steps.parse.outputs.changed-moose-mpi-rocky8-clang }}
      changed-moose-mpi-rocky8-cuda-gcc: ${{ steps.parse.outputs.changed-moose-mpi-rocky8-cuda-gcc }}
      changed-moose-mpi-rocky8-gcc: ${{ steps.parse.outputs.changed-moose-mpi-rocky8-gcc }}
      changed-moose-mpi-rocky8-gccmin: ${{ steps.parse.outputs.changed-moose-mpi-rocky8-gccmin }}
      changed-moose-mpi-rocky8-oneapi: ${{ steps.parse.outputs.changed-moose-mpi-rocky8-oneapi }}
      changed-moose-mpi-rocky9-gcc: ${{ steps.parse.outputs.changed-moose-mpi-rocky9-gcc }}
      changed-moose-mpi-ubuntu24-cuda-gcc: ${{ steps.parse.outputs.changed-moose-mpi-ubuntu24-cuda-gcc }}
      changed-moose-mpi-ubuntu24-gcc: ${{ steps.parse.outputs.changed-moose-mpi-ubuntu24-gcc }}
      uri-moose-base-rocky8: ${{ steps.parse.outputs.uri-moose-base-rocky8 }}
      uri-moose-base-rocky9: ${{ steps.parse.outputs.uri-moose-base-rocky9 }}
      uri-moose-base-rocky8-cuda: ${{ steps.parse.outputs.uri-moose-base-rocky8-cuda }}
      uri-moose-base-ubuntu24: ${{ steps.parse.outputs.uri-moose-base-ubuntu24 }}
      uri-moose-base-ubuntu24-cuda: ${{ steps.parse.outputs.uri-moose-base-ubuntu24-cuda }}
      uri-moose-compiler-rocky8-cuda-gcc: ${{ steps.parse.outputs.uri-moose-compiler-rocky8-cuda-gcc }}
      uri-moose-compiler-rocky8-gcc: ${{ steps.parse.outputs.uri-moose-compiler-rocky8-gcc }}
      uri-moose-compiler-rocky9-gcc: ${{ steps.parse.outputs.uri-moose-compiler-rocky9-gcc }}
      uri-moose-compiler-ubuntu24-gcc: ${{ steps.parse.outputs.uri-moose-compiler-ubuntu24-gcc }}
      uri-moose-compiler-ubuntu24-cuda-gcc: ${{ steps.parse.outputs.uri-moose-compiler-ubuntu24-cuda-gcc }}
      uri-moose-mpi-rocky8-clang: ${{ steps.parse.outputs.uri-moose-mpi-rocky8-clang }}
      uri-moose-mpi-rocky8-cuda-gcc: ${{ steps.parse.outputs.uri-moose-mpi-rocky8-cuda-gcc }}
      uri-moose-mpi-rocky8-gcc: ${{ steps.parse.outputs.uri-moose-mpi-rocky8-gcc }}
      uri-moose-mpi-rocky8-gccmin: ${{ steps.parse.outputs.uri-moose-mpi-rocky8-gccmin }}
      uri-moose-mpi-rocky8-oneapi: ${{ steps.parse.outputs.uri-moose-mpi-rocky8-oneapi }}
      uri-moose-mpi-rocky9-gcc: ${{ steps.parse.outputs.uri-moose-mpi-rocky9-gcc }}
      uri-moose-mpi-ubuntu24-cuda-gcc: ${{ steps.parse.outputs.uri-moose-mpi-ubuntu24-cuda-gcc }}
      uri-moose-mpi-ubuntu24-gcc: ${{ steps.parse.outputs.uri-moose-mpi-ubuntu24-gcc }}
      package-clang-rocky8: ${{ steps.parse.outputs.package-clang-rocky8 }}
      package-cuda: ${{ steps.parse.outputs.package-cuda }}
      package-gcc-min-rocky8: ${{ steps.parse.outputs.package-gcc-min-rocky8 }}
      package-gcc-rocky8: ${{ steps.parse.outputs.package-gcc-rocky8 }}
      package-gcc-rocky8-clang: ${{ steps.parse.outputs.package-gcc-rocky8-clang }}
      package-gcc-rocky9: ${{ steps.parse.outputs.package-gcc-rocky9 }}
      package-gcc-ubuntu24: ${{ steps.parse.outputs.package-gcc-ubuntu24 }}
      package-mpich: ${{ steps.parse.outputs.package-mpich }}
      package-mpich-rocky8-oneapi: ${{ steps.parse.outputs.package-mpich-rocky8-oneapi }}
      package-mpich-rocky9: ${{ steps.parse.outputs.package-mpich-rocky9 }}
      package-oneapi: ${{ steps.parse.outputs.package-oneapi }}
      package-openmpi: ${{ steps.parse.outputs.package-openmpi }}
      package-oras: ${{ steps.parse.outputs.package-oras }}
      package-rocky8: ${{ steps.parse.outputs.package-rocky8 }}
      package-rocky9: ${{ steps.parse.outputs.package-rocky9 }}
      package-ubuntu24: ${{ steps.parse.outputs.package-ubuntu24 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install python dependencies
        shell: bash
        run: pip install --no-cache -r requirements.txt
      - name: Parse
        id: parse
        shell: bash
        run: |
          prepare_cmd=("python" "./.github/scripts/prepare.py")
          prepare_args=("${{ github.event.pull_request.base.sha }}" "--github-token" "${{ secrets.GITHUB_TOKEN }}")
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            "${prepare_cmd[@]}" pr "${{ github.event.pull_request.number }}" "${prepare_args[@]}"
          elif [ "$GITHUB_EVENT_NAME" == "push" ]; then
            "${prepare_cmd[@]}" push "${prepare_args[@]}"
          fi

  moose-base-rocky8:
    name: "moose-base-rocky8"
    needs: [prepare]
    if: >-
      !cancelled()
      && needs.prepare.outputs.changed-moose-base-rocky8
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        uses: ./.github/actions/build
        with:
          registry-token: ${{ secrets.GITHUB_TOKEN }}
          context: docker/moose-base
          file: docker/moose-base/rocky8/Dockerfile
          uri: ${{ needs.prepare.outputs.uri-moose-base-rocky8 }}
          build-args: |
            ROCKY_VERSION=${{ needs.prepare.outputs.package-rocky8 }}
            ORAS_VERSION=${{ needs.prepare.outputs.package-oras }}

  moose-base-rocky8-cuda:
    name: "moose-base-rocky8-cuda"
    needs: [prepare]
    if: >-
      !cancelled()
      && needs.prepare.outputs.changed-moose-base-rocky8-cuda
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        uses: ./.github/actions/build
        with:
          registry-token: ${{ secrets.GITHUB_TOKEN }}
          context: docker/moose-base
          file: docker/moose-base/rocky8-cuda/Dockerfile
          uri: ${{ needs.prepare.outputs.uri-moose-base-rocky8-cuda }}
          build-args: |
            CUDA_VERSION=${{ needs.prepare.outputs.package-cuda }}
            ROCKY_VERSION=${{ needs.prepare.outputs.package-rocky8 }}
            ORAS_VERSION=${{ needs.prepare.outputs.package-oras }}

  moose-base-rocky9:
    name: "moose-base-rocky9"
    needs: [prepare]
    if: >-
      !cancelled()
      && needs.prepare.outputs.changed-moose-base-rocky9
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        uses: ./.github/actions/build
        with:
          registry-token: ${{ secrets.GITHUB_TOKEN }}
          context: docker/moose-base
          file: docker/moose-base/rocky9/Dockerfile
          uri: ${{ needs.prepare.outputs.uri-moose-base-rocky9 }}
          build-args: |
            ROCKY_VERSION=${{ needs.prepare.outputs.package-rocky9 }}
            ORAS_VERSION=${{ needs.prepare.outputs.package-oras }}

  # moose-base-ubuntu24:
  #   name: "moose-base-ubuntu24"
  #   needs: [prepare]
  #   if: >-
  #     !cancelled()
  #     && needs.prepare.outputs.changed-moose-base-ubuntu24
  #   runs-on: ubuntu-24.04
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v6
  #     - name: Build
  #       uses: ./.github/actions/build
  #       with:
  #         registry-token: ${{ secrets.GITHUB_TOKEN }}
  #         context: docker/moose-base
  #         file: docker/moose-base/ubuntu24/Dockerfile
  #         uri: ${{ needs.prepare.outputs.uri-moose-base-ubuntu24 }}
  #         build-args: |
  #           UBUNTU_VERSION=${{ needs.prepare.outputs.package-ubuntu24 }}
  #           ORAS_VERSION=${{ needs.prepare.outputs.package-oras }}

  # moose-base-ubuntu24-cuda:
  #   name: "moose-base-ubuntu24-cuda"
  #   needs: [prepare]
  #   if: >-
  #     !cancelled()
  #     && needs.prepare.outputs.changed-moose-base-ubuntu24-cuda
  #   runs-on: ubuntu-24.04
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v6
  #     - name: Build
  #       uses: ./.github/actions/build
  #       with:
  #         registry-token: ${{ secrets.GITHUB_TOKEN }}
  #         context: docker/moose-base
  #         file: docker/moose-base/ubuntu24-cuda/Dockerfile
  #         uri: ${{ needs.prepare.outputs.uri-moose-base-ubuntu24-cuda }}
  #         build-args: |
  #           CUDA_VERSION=${{ needs.prepare.outputs.package-cuda }}
  #           UBUNTU_VERSION=${{ needs.prepare.outputs.package-ubuntu24 }}
  #           ORAS_VERSION=${{ needs.prepare.outputs.package-oras }}

  moose-compiler-rocky8-gcc:
    name: "moose-compiler-rocky8-gcc"
    needs: [prepare, moose-base-rocky8]
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.moose-base-rocky8.result)
      && needs.prepare.outputs.changed-moose-compiler-rocky8-gcc
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        uses: ./.github/actions/build
        with:
          registry-token: ${{ secrets.GITHUB_TOKEN }}
          context: docker/moose-compiler/rocky-gcc
          file: docker/moose-compiler/rocky-gcc/Dockerfile
          uri: ${{ needs.prepare.outputs.uri-moose-compiler-rocky8-gcc }}
          build-args: |
            BUILD_FROM=${{ needs.prepare.outputs.uri-moose-base-rocky8 }}
            GCC_VERSION=${{ needs.prepare.outputs.package-gcc-rocky8 }}

  moose-compiler-rocky8-cuda-gcc:
    name: "moose-compiler-rocky8-cuda-gcc"
    needs: [prepare, moose-base-rocky8-cuda]
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.moose-base-rocky8-cuda.result)
      && needs.prepare.outputs.changed-moose-compiler-rocky8-cuda-gcc
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        uses: ./.github/actions/build
        with:
          registry-token: ${{ secrets.GITHUB_TOKEN }}
          context: docker/moose-compiler/rocky-gcc
          file: docker/moose-compiler/rocky-gcc/Dockerfile
          uri: ${{ needs.prepare.outputs.uri-moose-compiler-rocky8-cuda-gcc }}
          build-args: |
            BUILD_FROM=${{ needs.prepare.outputs.uri-moose-base-rocky8-cuda }}
            GCC_VERSION=${{ needs.prepare.outputs.package-gcc-rocky8 }}

  moose-compiler-rocky9-gcc:
    name: "moose-compiler-rocky9-gcc"
    needs: [prepare, moose-base-rocky9]
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.moose-base-rocky9.result)
      && needs.prepare.outputs.changed-moose-compiler-rocky9-gcc
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        uses: ./.github/actions/build
        with:
          registry-token: ${{ secrets.GITHUB_TOKEN }}
          context: docker/moose-compiler/rocky-gcc
          file: docker/moose-compiler/rocky-gcc/Dockerfile
          uri: ${{ needs.prepare.outputs.uri-moose-compiler-rocky9-gcc }}
          build-args: |
            BUILD_FROM=${{ needs.prepare.outputs.uri-moose-base-rocky9 }}
            GCC_VERSION=${{ needs.prepare.outputs.package-gcc-rocky9 }}

  # moose-compiler-ubuntu24-gcc:
  #   name: "moose-compiler-ubuntu24-gcc"
  #   needs: [prepare, moose-base-ubuntu24]
  #   runs-on: ubuntu-24.04
  #   if: >-
  #     !cancelled()
  #     && contains(fromJSON('["success", "skipped"]'), needs.moose-base-ubuntu24.result)
  #     && needs.prepare.outputs.changed-moose-compiler-ubuntu24-gcc
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v6
  #     - name: Build
  #       uses: ./.github/actions/build
  #       with:
  #         registry-token: ${{ secrets.GITHUB_TOKEN }}
  #         context: docker/moose-compiler/ubuntu-gcc
  #         file: docker/moose-compiler/ubuntu-gcc/Dockerfile
  #         uri: ${{ needs.prepare.outputs.uri-moose-compiler-ubuntu24-gcc }}
  #         build-args: |
  #           BUILD_FROM=${{ needs.prepare.outputs.uri-moose-base-ubuntu24 }}
  #           GCC_VERSION=${{ needs.prepare.outputs.package-gcc-ubuntu24 }}

  # moose-compiler-ubuntu24-cuda-gcc:
  #   name: "moose-compiler-ubuntu24-cuda-gcc"
  #   needs: [prepare, moose-base-ubuntu24-cuda]
  #   if: >-
  #     !cancelled()
  #     && contains(fromJSON('["success", "skipped"]'), needs.moose-base-ubuntu24-cuda.result)
  #     && needs.prepare.outputs.changed-moose-compiler-ubuntu24-cuda-gcc
  #   runs-on: ubuntu-24.04
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v6
  #     - name: Build
  #       uses: ./.github/actions/build
  #       with:
  #         registry-token: ${{ secrets.GITHUB_TOKEN }}
  #         context: docker/moose-compiler/ubuntu-gcc
  #         file: docker/moose-compiler/ubuntu-gcc/Dockerfile
  #         uri: ${{ needs.prepare.outputs.uri-moose-compiler-ubuntu24-cuda-gcc }}
  #         build-args: |
  #           BUILD_FROM=${{ needs.prepare.outputs.uri-moose-base-ubuntu24-cuda }}
  #           GCC_VERSION=${{ needs.prepare.outputs.package-gcc-ubuntu24 }}

  moose-mpi-rocky8-clang:
    name: "moose-mpi-rocky8-clang"
    needs: [prepare, moose-base-rocky8]
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.moose-base-rocky8.result)
      && needs.prepare.outputs.changed-moose-mpi-rocky8-clang
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        uses: ./.github/actions/build
        with:
          registry-token: ${{ secrets.GITHUB_TOKEN }}
          context: docker/moose-mpi
          file: docker/moose-mpi/rocky8-clang/Dockerfile
          uri: ${{ needs.prepare.outputs.uri-moose-mpi-rocky8-clang }}
          build-args: |
            BUILD_FROM=${{ needs.prepare.outputs.uri-moose-base-rocky8 }}
            CLANG_VERSION=${{ needs.prepare.outputs.package-clang-rocky8 }}
            GCC_VERSION=${{ needs.prepare.outputs.package-gcc-rocky8-clang }}
            MPICH_VERSION=${{ needs.prepare.outputs.package-mpich }}

  moose-mpi-rocky8-cuda-gcc:
    name: "moose-mpi-rocky8-cuda-gcc"
    needs: [prepare, moose-compiler-rocky8-cuda-gcc]
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.moose-compiler-rocky8-cuda-gcc.result)
      && needs.prepare.outputs.changed-moose-mpi-rocky8-cuda-gcc
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        uses: ./.github/actions/build
        with:
          registry-token: ${{ secrets.GITHUB_TOKEN }}
          context: docker/moose-mpi
          file: docker/moose-mpi/rocky-gcc/Dockerfile
          uri: ${{ needs.prepare.outputs.uri-moose-mpi-rocky8-cuda-gcc }}
          build-args: |
            BUILD_FROM=${{ needs.prepare.outputs.uri-moose-compiler-rocky8-cuda-gcc }}
            MPICH_VERSION=${{ needs.prepare.outputs.package-mpich }}
            MPICH_ARGS="--with-device=ch4:ucx"
            OPENMPI_VERSION=${{ needs.prepare.outputs.package-openmpi }}

  moose-mpi-rocky8-gcc:
    name: "moose-mpi-rocky8-gcc"
    needs: [prepare, moose-compiler-rocky8-gcc]
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.moose-compiler-rocky8-gcc.result)
      && needs.prepare.outputs.changed-moose-mpi-rocky8-gcc
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        uses: ./.github/actions/build
        with:
          registry-token: ${{ secrets.GITHUB_TOKEN }}
          context: docker/moose-mpi
          file: docker/moose-mpi/rocky-gcc/Dockerfile
          uri: ${{ needs.prepare.outputs.uri-moose-mpi-rocky8-gcc }}
          build-args: |
            BUILD_FROM=${{ needs.prepare.outputs.uri-moose-compiler-rocky8-gcc }}
            MPICH_VERSION=${{ needs.prepare.outputs.package-mpich }}
            OPENMPI_VERSION=${{ needs.prepare.outputs.package-openmpi }}

  moose-mpi-rocky8-gccmin:
    name: "moose-mpi-rocky8-gccmin"
    needs: [prepare, moose-base-rocky8]
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.moose-base-rocky8.result)
      && needs.prepare.outputs.changed-moose-mpi-rocky8-gccmin
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        uses: ./.github/actions/build
        with:
          registry-token: ${{ secrets.GITHUB_TOKEN }}
          context: docker/moose-mpi
          file: docker/moose-mpi/rocky8-gccmin/Dockerfile
          uri: ${{ needs.prepare.outputs.uri-moose-mpi-rocky8-gccmin }}
          build-args: |
            BUILD_FROM=${{ needs.prepare.outputs.uri-moose-base-rocky8 }}
            GCC_VERSION=${{ needs.prepare.outputs.package-gcc-min-rocky8 }}
            MPICH_VERSION=${{ needs.prepare.outputs.package-mpich }}

  moose-mpi-rocky8-oneapi:
    name: "moose-mpi-rocky8-oneapi"
    needs: [prepare, moose-compiler-rocky8-gcc]
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.moose-compiler-rocky8-gcc.result)
      && needs.prepare.outputs.changed-moose-mpi-rocky8-oneapi
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        uses: ./.github/actions/build
        with:
          registry-token: ${{ secrets.GITHUB_TOKEN }}
          context: docker/moose-mpi
          file: docker/moose-mpi/rocky8-oneapi/Dockerfile
          uri: ${{ needs.prepare.outputs.uri-moose-mpi-rocky8-oneapi }}
          build-args: |
            BUILD_FROM=${{ needs.prepare.outputs.uri-moose-compiler-rocky8-gcc }}
            ONEAPI_VERSION=${{ needs.prepare.outputs.package-oneapi }}
            MPICH_VERSION=${{ needs.prepare.outputs.package-mpich-rocky8-oneapi }}

  moose-mpi-rocky9-gcc:
    name: "moose-mpi-rocky9-gcc"
    needs: [prepare, moose-compiler-rocky9-gcc]
    if: >-
      !cancelled()
      && contains(fromJSON('["success", "skipped"]'), needs.moose-compiler-rocky9-gcc.result)
      && needs.prepare.outputs.changed-moose-mpi-rocky9-gcc
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        uses: ./.github/actions/build
        with:
          registry-token: ${{ secrets.GITHUB_TOKEN }}
          context: docker/moose-mpi
          file: docker/moose-mpi/rocky-gcc/Dockerfile
          uri: ${{ needs.prepare.outputs.uri-moose-mpi-rocky9-gcc }}
          build-args: |
            BUILD_FROM=${{ needs.prepare.outputs.uri-moose-compiler-rocky9-gcc }}
            MPICH_VERSION=${{ needs.prepare.outputs.package-mpich-rocky9 }}
            OPENMPI_VERSION=${{ needs.prepare.outputs.package-openmpi }}

  # moose-mpi-ubuntu24-cuda-gcc:
  #   name: "moose-mpi-ubuntu24-cuda-gcc"
  #   needs: [prepare, moose-compiler-ubuntu24-cuda-gcc]
  #   if: >-
  #     !cancelled()
  #     && contains(fromJSON('["success", "skipped"]'), needs.moose-compiler-ubuntu24-cuda-gcc.result)
  #     && needs.prepare.outputs.changed-moose-mpi-ubuntu24-cuda-gcc
  #   runs-on: ubuntu-24.04
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v6
  #     - name: Build
  #       uses: ./.github/actions/build
  #       with:
  #         registry-token: ${{ secrets.GITHUB_TOKEN }}
  #         context: docker/moose-mpi
  #         file: docker/moose-mpi/ubuntu-gcc/Dockerfile
  #         uri: ${{ needs.prepare.outputs.uri-moose-mpi-ubuntu24-cuda-gcc }}
  #         build-args: |
  #           BUILD_FROM=${{ needs.prepare.outputs.uri-moose-compiler-ubuntu24-cuda-gcc }}
  #           MPICH_VERSION=${{ needs.prepare.outputs.package-mpich }}
  #           OPENMPI_VERSION=${{ needs.prepare.outputs.package-openmpi }}

  # moose-mpi-ubuntu24-gcc:
  #   name: "moose-mpi-ubuntu24-gcc"
  #   needs: [prepare, moose-compiler-ubuntu24-gcc]
  #   if: >-
  #     !cancelled()
  #     && contains(fromJSON('["success", "skipped"]'), needs.moose-compiler-ubuntu24-gcc.result)
  #     && needs.prepare.outputs.changed-moose-mpi-ubuntu24-gcc
  #   runs-on: ubuntu-24.04
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v6
  #     - name: Build
  #       uses: ./.github/actions/build
  #       with:
  #         registry-token: ${{ secrets.GITHUB_TOKEN }}
  #         context: docker/moose-mpi
  #         file: docker/moose-mpi/ubuntu-gcc/Dockerfile
  #         uri: ${{ needs.prepare.outputs.uri-moose-mpi-ubuntu24-gcc }}
  #         build-args: |
  #           BUILD_FROM=${{ needs.prepare.outputs.uri-moose-compiler-ubuntu24-gcc }}
  #           MPICH_VERSION=${{ needs.prepare.outputs.package-mpich }}
  #           OPENMPI_VERSION=${{ needs.prepare.outputs.package-openmpi }}
