name: Delete untagged images

on:
  workflow_dispatch:
  # Daily at 2 AM
  schedule:
    - cron: "0 2 * * *"
      timezone: "America/Denver"

jobs:
  delete:
    runs-on: ubuntu-slim
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install python
        shell: bash
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv sync --frozen
      - name: Deleted
        shell: bash
        env:
          PYTHONUNBUFFERED: 1
        run: |
          source .venv/bin/activate
          python ./.github/scripts/ci.py \
            delete_untagged \
            --github-token ${{ github.token }}
