name: Delete untagged images

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Deleted untagged images
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: bash .github/scripts/delete-untagged-images.bash
